// This file is auto-generated by tools/gen_ops.py
// Do not edit manually!

use crate::ops::OperatorKind;
use crate::py::operator::Operator;
use pyo3::prelude::*;

/// Static factory class for creating Operators
#[pyclass(frozen, name = "Op")]
pub struct Op;

#[pymethods]
impl Op {
    #[staticmethod]
    pub fn assert_str() -> Operator {
        Operator {
            kind: OperatorKind::AssertStr,
        }
    }

    #[staticmethod]
    pub fn expect_str() -> Operator {
        Operator {
            kind: OperatorKind::ExpectStr,
        }
    }

    #[staticmethod]
    pub fn split(delim: String) -> Operator {
        Operator {
            kind: OperatorKind::Split { delim },
        }
    }

    #[staticmethod]
    pub fn index(idx: usize) -> Operator {
        Operator {
            kind: OperatorKind::Index { idx },
        }
    }

    #[staticmethod]
    pub fn get(key: String) -> Operator {
        Operator {
            kind: OperatorKind::GetKey { key },
        }
    }

    #[staticmethod]
    pub fn to_uppercase() -> Operator {
        Operator {
            kind: OperatorKind::ToUppercase,
        }
    }

    #[staticmethod]
    pub fn len() -> Operator {
        Operator {
            kind: OperatorKind::Len,
        }
    }
}
